# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: car.proto for package 'car'

require 'grpc'
require 'car_pb'

module Car
  module Carchecker
    # The car control service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'car.Carchecker'

      rpc :carCheck, Google::Protobuf::Empty, CarStatus
    end

    Stub = Service.rpc_stub_class
  end
end
